routes/web.php
#$this->name('login')->get('/', 'Auth\LoginController@showLoginForm');
$this->post('/login', 'Auth\LoginController@login')->name('login');

Route::prefix('tf')
->middleware(['center.check'])
->group(function(){
	$this->get('/', 'Auth\LoginController@index');
	$this->get('{center}', 'Auth\LoginController@showLoginForm')->name('center.login');
});


Route::prefix('password')
->group(function(){
	$this->get('reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	$this->post('reset', 'Auth\ResetPasswordController@reset');
	$this->get('reset/{token}/{u?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

	// via sq
	$this->get('security', 'Auth\ForgotPasswordController@security')->name('password.security');
	$this->post('security/request', 'Auth\ForgotPasswordController@submitUsername')->name('password.security.request');
	$this->get('security/question/{q}', 'Auth\ForgotPasswordController@request')->name('password.security.question');
	$this->post('security/reset', 'Auth\ForgotPasswordController@submitSecurity')->name('password.security.reset');

	// via email
	$this->post('email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes [/]
|--------------------------------------------------------------------------
*/
Route::prefix('portal')
->middleware(['auth', 'noob'])
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');

	$this->get('/', 'HomeController@index')->name('home');
	$this->get('schedule/{id}', 'HomeController@schedule_json')->name('schedule_json');
    /*
	|--------------------------------------------------------------------------
	| Mail Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('mail')
	->group(function(){
		Route::get('welcome', 'MailController@sendWelcomeMail')->name('mail.welcome');
	});
    /*
	|--------------------------------------------------------------------------
	| Starter Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('start')
	->middleware('start')
	->group(function(){
		Route::get('/', 'StartController@start')->name('start');
		Route::get('reset', 'StartController@reset')->name('start.reset');
		Route::post('reset', 'StartController@submitReset')->name('start.submitReset');
		Route::get('security', 'StartController@security')->name('start.security');
		Route::post('security', 'StartController@submitSecurity')->name('start.submitSecurity');
	});

	/*
	|--------------------------------------------------------------------------
	| Admin Routes
	|--------------------------------------------------------------------------
	*/
	#Route::resource('users', 'UsersController', [ 'roles' => ['administrator'] ]);

	
	/*
	|--------------------------------------------------------------------------
	| Schedule Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('schedules')
    ->middleware('root')
	->group(function(){
		Route::name('ss_center_we')->get('week-ending/{center_id?}', 'ShiftSwapSchedulesController@center_week_ending');
		Route::name('ss_center_schedule')->get('records/{center_id?}/{week_ending?}', 'ShiftSwapSchedulesController@center_schedule');
	});
	Route::resource('schedules', 'ShiftSwapSchedulesController', [ 'roles' => ['administrator'] ]);

	
	/*
	|--------------------------------------------------------------------------
	| Root Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('admin')
    	->middleware('root')
		->group(function(){
		Route::name('impersonate')->get('impersonate/take/{userid}', 'Admin\ImpersonateController@take', ['as' => 'admin']);

    	Route::prefix('user')
		->group(function(){
			Route::resource('upload', 'Admin\UsersUploadController', ['as' => 'user'])->only(['index', 'store']);
			#Route::name('user.upload')->get('upload', 'Admin\UsersUploadController@create');
			#Route::name('user.upload-submit')->get('upload-submit', 'Admin\UsersUploadController@store');
			Route::name('user.generate-password')->get('generate-password/{id}', 'Admin\UsersController@generate_password');
		});

		Route::resource('user', 'Admin\UsersController', ['as' => 'admin']);
		Route::resource('schedule', 'Admin\SchedulesController', ['as' => 'admin']);
		Route::resource('mail-recipients', 'Admin\MailRecipientsController', ['as' => 'admin']);
		Route::get('password-generator/{number?}', 'Admin\PasswordGeneratorController@index', ['as' => 'admin'])->name('admin.password-generator.index');

		Route::name('home-password')->get('passwords/{number}', 'HomeController@passwords');
	});

	Route::name('impersotate.leave')->get('impersonate/leave', 'Admin\ImpersonateController@leave', ['as' => 'admin'])->middleware(['start']);
	/*
	|--------------------------------------------------------------------------
	| Shift Swap Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('shift-swap')
	->group(function(){
		Route::get('search', 'ShiftSwapInformationController@search_json')->name('ss_search_json');
		Route::get('details-json/{id}', 'ShiftSwapInformationController@details_json')->name('ss_details_json');
		Route::get('record/{id?}', 'ShiftSwapInformationController@shift_swap_record')->name('ss_request_history_json');
		Route::get('week-ending-and-my-shift-date/{id}', 'ShiftSwapInformationController@ss_we_and_my_sd')->name('ss_we_and_my_sd');
		#Route::get('buddy-shift-date', 'ShiftSwapInformationController@ss_buddy_shift_date')->name('ss_buddy_shift_date');

		Route::post('request-confirmation', 'ShiftSwapController@request_confirmation')->name('ss_confirmation');

		Route::get('history/{type}', 'ShiftSwapMyRequestController@index')->name('ss_history');

		Route::group(['middleware' => 'admin'], function(){
	    	Route::resource('ss-reports', 'ShiftSwapReportsController')->only(['index', 'show']);


			Route::get('schedule-upload/utilization', 'ShiftSwapScheduleUploadController@utilization')->name('schedule-upload.utilization');
	    	Route::resource('schedule-upload', 'ShiftSwapScheduleUploadController')->only(['index', 'store']);
	    	Route::resource('enterprise-reports', 'ShiftSwapReportsEnterpriseController')->only(['index', 'show']);
		});
	});
	Route::resource('shift-swap', 'ShiftSwapController')->only(['index', 'store']);
	/*
	|--------------------------------------------------------------------------
	| VTO Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('forecast')
	->group(function(){
		Route::name('forecast.calendar')->get('calendar', 'ForecastController@calendar');
		Route::name('forecast.list')->get('list/{date?}', 'ForecastController@list');
		Route::get('skills-wps-json/{center?}', 'ForecastController@skills_wps_json')->name('skills_wps_json');

	    Route::prefix('vot')
		->group(function(){
			Route::name('vot.calendar')->get('calendar', 'ForecastVOTController@calendar');
			Route::name('vot.list')->get('list/{date?}/{schedule?}', 'ForecastVOTController@list');
			Route::name('vot.submit')->post('submit', 'ForecastVOTController@submit');
		});
		Route::resource('vot', 'ForecastVOTController');

	    Route::prefix('vto')
		->group(function(){
			Route::name('vto.calendar')->get('calendar', 'ForecastVTOController@calendar');
			Route::name('vto.list')->get('list/{date?}/{schedule?}', 'ForecastVTOController@list');
			Route::name('vto.submit')->post('submit', 'ForecastVTOController@submit');
			Route::name('vto.mail')->get('mail', 'ForecastCronJobController@vto_email');
		});
		Route::resource('vto', 'ForecastVTOController');

		Route::group(['middleware' => 'admin'], function(){
			Route::resource('vf-reports', 'ForecastReportsController')->only(['index', 'show']);
			Route::resource('vot-enterprise-reports', 'ForecastReportsEnterpriseController')->only(['index', 'show']);
		});
		Route::resource('utilization', 'ForecastUtilizationController', ['as' => 'forecast'])->only(['index', 'create']);
		Route::resource('utilization-detailed', 'ForecastUtilizationDetailedController', ['as' => 'forecast'])->only(['create']);
		Route::resource('upload', 'ForecastUploadController', ['as' => 'forecast'])->only(['index', 'store']);
	});
	Route::resource('forecast', 'ForecastController')->only(['index', 'create', 'store']);
	/*
	|--------------------------------------------------------------------------
	| Absence Replacement
	|--------------------------------------------------------------------------
	*/
    Route::prefix('absence')
	->group(function(){
		Route::name('absence.calendar')->get('calendar', 'AbsenceController@calendar');
		Route::name('absence.list')->get('list', 'AbsenceController@list');
		Route::name('absence.application')->get('application/{shift_date}/{schedule}', 'AbsenceController@application');
		Route::name('absence.application_post')->post('application', 'AbsenceController@application_post');
		Route::name('absence.approve')->get('{id}/{absence_id}/approve', 'AbsenceController@approve');
		Route::name('absence.deny')->get('{id}/{absence_id}/deny', 'AbsenceController@deny');

		Route::resource('replacement', 'AbsenceReplacementController');
	});
	Route::resource('absence', 'AbsenceController');
	/*
	|--------------------------------------------------------------------------
	| VTO Routes
	|--------------------------------------------------------------------------
	*/
	Route::get('account/download', 'UserAccountController@download')->name('account.download');
	Route::resource('account', 'UserAccountController')->only(['store', 'edit', 'update']);
});

Route::prefix('cron')
->group(function(){
	Route::name('vot.mail')->get('vot-mail', 'ForecastCronJobController@vot_email');

resources/views/vforecast/reports/enterprise.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
  <div class="columns">
    <div class="column is-3"></div>
    <div class="column is-6">
      <div class="card">
        <div class="card-header">
          <label class="card-header-title label" for="search_avaya">Download Forecasted VTO/VOT</label>
        </div>
        <div class="card-content">
          @include('partials.error-message')
          <form id="ss-download" method="get" action="{{ route('vot-enterprise-reports.show', str_random(10)) }}">
			<div class="field is-horizontal">
				<div class="field-label is-normal">
					<label class="label" for="type">Forecast Type</label>
				</div>
				<div class="field-body">
					<div class="field">
						<div class="control">
							<div class="select is-fullwidth">
								<select id="type" name="type">
									<option value="">-- Select --</option>
									<option value="ot">Overtime</option>
									<option value="to">Time-Off</option>
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="field is-horizontal">
				<div class="field-label is-normal">
					<label class="label" for="center_id">Center</label>
				</div>
				<div class="field-body">
					<div class="field">
						<div class="control">
							<div class="select is-fullwidth">
								<select id="center_id" name="center_id">
									<option value="0">-- Select All --</option>
									@foreach($centers as $row)
										<option value="{{ $row->id }}">{{ $row->name }}</option>
									@endforeach
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="field is-horizontal">
				<div class="field-label is-normal">
				<label class="label" for="organization" title="Organization">Org</label>
				</div>
				<div class="field-body">
					<div class="field">
						<div class="control">
							<div class="select is-fullwidth">
							<select id="organization" name="organization">
								<option value="">-- Select All --</option>
							</select>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="field is-horizontal">
				<div class="field-label is-normal">
					<label class="label" for="shift_date">Shift Date</label>
				</div>
				<div class="field-body">
					<div class="field">
						<div class="control has-icons-left is-expanded">
							<input class="input" type="text" id="shift_date" name="shift_date" autocomplete="off" />
							<span class="icon is-small is-left">
								<i class="fa fa-calendar"></i>
							</span>
						</div>
					</div>
				</div>
			</div>

			<div class="field is-horizontal">
				<div class="field-label is-normal">
					<label class="label" for="shift_date">&nbsp;</label>
				</div>
				<div class="field-body">
					<div class="field">
						<div class="control has-icons-left is-expanded">
							{!! csrf_field() !!}
							<button class="button is-info" type="submit">Download</button>
						</div>
					</div>
				</div>
			</div>
          </form>
        </div>
      </div>
    </div>
    <div class="column is-3"></div>
  </div>
</div>

@endsection

@section('scripts')
  <script>
    // bulmaCalendar.attach('#shift_date');
    	skills_wps(0);
    	$('#shift_date').datepicker();
				var option_select_default = '<option value="">-- Select All --</option>';
				var xhr_skills_wps = null;

				$('#center_id').change(function(){
					var center = $(this).val();
					if(center != '')
					{
						skills_wps(center);
					}
					else
					{
							$('#organization, #wp').html(option_select_default);
					}
			});

			function skills_wps(center)
			{
					xhr_skills_wps = $.ajax({
					type : 'get',
					url : '{{ route("skills_wps_json") }}/' + center,
					cache : false,
					dataType : "json",
							beforeSend: function(xhr){
								if (xhr_skills_wps != null)
								{
									xhr_skills_wps.abort();
								}
							}
					}).done(function(result) {
						var skills = option_select_default;
						var wps = option_select_default;
					$.each(result['skills'], function(key, value){
						skills += '<option value="' + value + '">' + value + '</option>';
					});
					$.each(result['wps'], function(key, value){
						wps += '<option value="' + value + '">' + value + '</option>';
					});
						$('#organization').html(skills);
						$('#wp').html(wps);
					}).fail(function(jqXHR, textStatus){
						//
					});
			}
  </script>
@endsection

@section('styles')
	<style>
		.field-label label {
			width: 105px;
		}
	</style>
@endsection

resources/views/vforecast/reports/index.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
  <div class="columns">
    <div class="column is-3"></div>
    <div class="column is-6">
      <div class="card">
        <div class="card-header">
          <label class="card-header-title label" for="search_avaya">Download Forecasted Voluntary Overtime/Timeoff</label>
        </div>
        <div class="card-content">
          @include('partials.error-message')
          <form id="ss-download" method="get" action="{{ route('vf-reports.show', str_random(10)) }}">

            <div class="field has-addons">
              <div class="control">
                <div class="select">
                  <select id="type" name="type">
                    <option value="">-- Select --</option>
                    <option value="ot">Overtime</option>
                    <option value="to">Timeoff</option>
                  </select>
                </div>
              </div>
              <div class="control has-icons-left is-expanded">
                <input class="input" type="text" id="date_confirmed" name="date_confirmed" autocomplete="off" />
                <span class="icon is-small is-left">
                  <i class="fa fa-calendar"></i>
                </span>
              </div>
              <div class="control">
                <button class="button is-info" type="submit">Download</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
    <div class="column is-3"></div>
  </div>
</div>

@endsection

@section('scripts')
  {{-- <script src="{{ asset('js/bulma-calendar.js') }}"></script> --}}
  <script>
    // bulmaCalendar.attach('#date_confirmed', {
    //   closeOnOverlayClick: true,
    //   closeOnSelect: true
    // });

    $('#date_confirmed').datepicker();
  </script>
@endsection

resources/views/vforecast/reports/utilization-download-detailed.blade.php
@foreach($dates as $date)
<table border="1" width="100%">
	<tr>
		<th colspan="4">{{ $date }}</th>
	</tr>
	@foreach($centers as $center)
	<tr>
		<th colspan="4" align="left">{{ $center->name }}</th>
	</tr>
	<tr>
		<th align="left">Organization</th>
		<th align="center">Type</th>
		<th align="center">Slot/s</th>
		<th align="center">Availed</th>
	</tr>
	<?php
	$center_id = $center->id;
	$organizations_first = App\ForecastVTO::whereCenterId($center_id)->whereShiftDate($date)->groupBy('organization')->orderBy('organization', 'ASC')->select([DB::raw('\'VTO\' AS forecast_type'), 'organization', DB::raw('SUM(slots) AS total_slots')]);

	$organizations = App\ForecastVOT::whereCenterId($center_id)->whereShiftDate($date)->groupBy('organization')->orderBy('organization', 'ASC')->union($organizations_first)->get([DB::raw('\'VOT\' AS forecast_type'), 'organization', DB::raw('SUM(slots) AS total_slots')]);
	?>
		@foreach($organizations as $row)
		<?php
		$organization = $row->organization;

		if ($row->forecast_type == 'VTO') {
			$availed = App\ForecastVTORequestItem::whereHas('forecast', function($query) use ($center_id, $date, $organization) {
				$query->whereCenterId($center_id)->whereShiftDate($date)->whereOrganization($organization);
			})->count('id');
		} else {
			$availed = App\ForecastVOTRequestItem::whereHas('forecast', function($query) use ($center_id, $date, $organization) {
				$query->whereCenterId($center_id)->whereShiftDate($date)->whereOrganization($organization);
			})->count('id');
		}
		?>
		<tr>
			<td align="left">{{ $organization }}</td>
			<td align="center">{{ $row->forecast_type }}</td>
			<td align="center">{{ $row->total_slots }}</td>
			<td align="center">{{ $availed }}</td>
		</tr>
		@endforeach
	<tr>
		<td colspan="4">&nbsp;</td>
	</tr>
	@endforeach
</table>
<br>
@endforeach

resources/views/vforecast/reports/utilization-download-old.blade.php
<?php
$second_col = '<tr>';
?>
<table border="1" width="100%">
	<tr>
		<th rowspan="2" align="left">Center</th>
		@foreach($dates as $date)
			<th colspan="6">{{ $date }}</th>
			<?php
			$second_col .= '<th align="center">Number of Agents</th><th align="center">VTO Availed</th><th align="center">VTO Offered</th><th align="center">Number of Agents</th><th align="center">VOT Availed</th><th align="center">VOT Offered</th>';
			?>
		@endforeach
	</tr>
	{!! $second_col . '</tr>' !!}
	@foreach($centers as $center)
	<tr>
		<th align="left">{{ $center->name }}</th>
		@foreach($dates as $date)
		<?php
		$center_id = $center->id;

		//Timeoff
		$vto_agent_count = App\ForecastVTORequest::whereHas('items.forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count('id');
		$vto_count = App\ForecastVTORequestItem::whereHas('forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count('id');
		$vto_forecasted_total = App\ForecastVTO::whereCenterId($center_id)->whereShiftDate($date)->sum('slots');

		// Overtime
		$vot_agent_count = App\ForecastVOTRequest::whereHas('items.forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count('id');
		$vot_count = App\ForecastVOTRequestItem::whereHas('forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count('id');
		$vot_forecasted_total = App\ForecastVOT::whereCenterId($center_id)->whereShiftDate($date)->sum('slots');
		?>
			<td align="center">{{ $vto_agent_count }}</td>
			<td align="center">{{ $vto_count }}</td>
			<th align="center">{{ $vto_forecasted_total }}</th>

			<td align="center">{{ $vot_agent_count }}</td>
			<td align="center">{{ $vot_count }}</td>
			<th align="center">{{ $vot_forecasted_total }}</th>
		@endforeach
	</tr>
	@endforeach
</table>

resources/views/vforecast/reports/utilization-download.blade.php
<?php
$second_col = '<tr>';
?>
<table border="1" width="100%">
	<tr>
		<th rowspan="2" align="left">Center</th>
		@foreach($dates as $date)
			<th colspan="6">{{ $date }}</th>
			<?php
			$second_col .= '<th align="center">Number of Agents</th><th align="center">VTO Availed</th><th align="center">VTO Offered</th><th align="center">Number of Agents</th><th align="center">VOT Availed</th><th align="center">VOT Offered</th>';
			?>
		@endforeach
	</tr>
	{!! $second_col . '</tr>' !!}
	@foreach($centers as $center)
	<tr>
		<th align="left">{{ $center->name }}</th>
		@foreach($dates as $date)
		<?php
		$center_id = $center->id;

		//Timeoff
		$vto_agent_count = App\ForecastVTORequest::whereHas('items.forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count(DB::raw('DISTINCT user_id'));
		$vto_count = App\ForecastVTORequestItem::whereHas('forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count('id');
		$vto_forecasted_total = App\ForecastVTO::whereCenterId($center_id)->whereShiftDate($date)->sum('slots');

		// Overtime
		$vot_agent_count = App\ForecastVOTRequest::whereHas('items.forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count(DB::raw('DISTINCT user_id'));
		$vot_count = App\ForecastVOTRequestItem::whereHas('forecast', function($query) use ($center_id, $date) {
			$query->whereCenterId($center_id)->whereShiftDate($date);
		})->count('id');
		$vot_forecasted_total = App\ForecastVOT::whereCenterId($center_id)->whereShiftDate($date)->sum('slots');
		?>
			<td align="center">{{ $vto_agent_count }}</td>
			<td align="center">{{ $vto_count }}</td>
			<th align="center">{{ $vto_forecasted_total }}</th>

			<td align="center">{{ $vot_agent_count }}</td>
			<td align="center">{{ $vot_count }}</td>
			<th align="center">{{ $vot_forecasted_total }}</th>
		@endforeach
	</tr>
	@endforeach
</table>

resources/views/vforecast/reports/utilization.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
  	<div class="columns">
    	<div class="column is-3"></div>
    	<div class="column is-6">

      		<div class="card">
		        <div class="card-header">
		          	<label class="card-header-title label" for="search_avaya">VOT/VTO Utilization</label>
		        </div>
		        <div class="card-content">
		          	@include('partials.error-message')
		          	<form id="ss-download" method="get" action="{{ route('forecast.utilization.create') }}">
						<div class="field is-horizontal">
							<div class="field-label is-normal">
								<label class="label" for="center_id">Forecast Type</label>
							</div>
							<div class="field-body">
								<div class="field">
									<div class="control">
										<div class="select is-fullwidth">
											<select id="center_id" name="center_id">
							                    <option value="">-- All --</option>
							                    @foreach($centers as $center)
							                    <option value="{{ $center->id }}">{{ $center->name }}</option>
							                    @endforeach
											</select>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="field is-horizontal">
							<div class="field-label is-normal">
								<label class="label" for="detailed_date_from">From</label>
							</div>
							<div class="field-body">
								<div class="field">
									<div class="control has-icons-left is-expanded">
										<input class="input" type="text" id="detailed_date_from" name="date_from" autocomplete="off" />
										<span class="icon is-small is-left">
											<i class="fa fa-calendar"></i>
										</span>
									</div>
								</div>
							</div>
						</div>

						<div class="field is-horizontal">
							<div class="field-label is-normal">
								<label class="label" for="detailed_date_to">To</label>
							</div>
							<div class="field-body">
								<div class="field">
									<div class="control has-icons-left is-expanded">
										<input class="input" type="text" id="detailed_date_to" name="date_to" autocomplete="off" />
										<span class="icon is-small is-left">
											<i class="fa fa-calendar"></i>
										</span>
									</div>
								</div>
							</div>
						</div>

						<div class="field is-horizontal">
							<div class="field-label is-normal"></div>
							<div class="field-body">
								<div class="field">
			                		<button class="button is-info" type="submit">Download</button>
								</div>
							</div>
						</div>
		          	</form>
		        </div>
		    </div>
		    <br>
      		<div class="card">
		        <div class="card-header">
		          	<label class="card-header-title label" for="search_avaya">VOT/VTO Utilization Detailed</label>
		        </div>
		        <div class="card-content">
		          	@include('partials.error-message')
		          	<form id="ss-download" method="get" action="{{ route('forecast.utilization-detailed.create') }}">
						<div class="field is-horizontal">
							<div class="field-label is-normal">
								<label class="label" for="center_id">Forecast Type</label>
							</div>
							<div class="field-body">
								<div class="field">
									<div class="control">
										<div class="select is-fullwidth">
											<select id="center_id" name="center_id">
							                    <option value="">-- All --</option>
							                    @foreach($centers as $center)
							                    <option value="{{ $center->id }}">{{ $center->name }}</option>
							                    @endforeach
											</select>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="field is-horizontal">
							<div class="field-label is-normal">
								<label class="label" for="date_from">From</label>
							</div>
							<div class="field-body">
								<div class="field">
									<div class="control has-icons-left is-expanded">
										<input class="input" type="text" id="date_from" name="date_from" autocomplete="off" />
										<span class="icon is-small is-left">
											<i class="fa fa-calendar"></i>
										</span>
									</div>
								</div>
							</div>
						</div>

						<div class="field is-horizontal">
							<div class="field-label is-normal">
								<label class="label" for="date_to">To</label>
							</div>
							<div class="field-body">
								<div class="field">
									<div class="control has-icons-left is-expanded">
										<input class="input" type="text" id="date_to" name="date_to" autocomplete="off" />
										<span class="icon is-small is-left">
											<i class="fa fa-calendar"></i>
										</span>
									</div>
								</div>
							</div>
						</div>

						<div class="field is-horizontal">
							<div class="field-label is-normal"></div>
							<div class="field-body">
								<div class="field">
			                		<button class="button is-info" type="submit">Download</button>
								</div>
							</div>
						</div>
		          	</form>
		        </div>
		    </div>

    	</div>
    	<div class="column is-3"></div>
  	</div>
</div>

@endsection

@section('scripts')
  <script>
    $('#date_from, #date_to, #detailed_date_from, #detailed_date_to').datepicker();
  </script>
@endsection

resources/views/vforecast/reports/voluntary-overtime.blade.php
<table border="1">
	<tr>
		<th colspan="9">{{ $file }}</th>
	</tr>
	<tr>
		<th>Request ID</th>
		<th>Avaya</th>
		<th>TAS Login</th>
		<th>Name</th>
		<th>Work Pattern</th>
		<th>Organization</th>
		<th>Shift Date</th>
		<th>Schedule Start</th>
		<th>Schedule End</th>
	</tr>
	@foreach($rows as $row)
		<tr>
			<td>{{ $row->id }}</td>
			<td>{{ $row->request->user->information->avaya }}</td>
			<td>{{ $row->request->user->username }}</td>
			<td>{{ $row->request->user->name }}</td>
			<td>{{ $row->request->user->information->wp }}</td>
			<td>{{ $row->request->user->information->skill }}</td>
			<td>{{ $row->forecast->shift_date }}</td>
			<td>{{ date('h:i A' ,strtotime($row->forecast->time_start)) }} </td>
			<td>{{ date('h:i A' ,strtotime($row->forecast->time_end)) }}</td>
		</tr>
	@endforeach
</table>

resources/views/vforecast/reports/voluntary-timeoff.blade.php
<table border="1">
	<tr>
		<th colspan="9">{{ $file }}</th>
	</tr>
	<tr>
		<th>Request ID</th>
		<th>Avaya</th>
		<th>TAS Login</th>
		<th>Name</th>
		<th>Work Pattern</th>
		<th>Organization</th>
		<th>Shift Date</th>
		<th>Schedule Start</th>
		<th>Schedule End</th>
	</tr>
	@foreach($rows as $row)
		<tr>
			<td>{{ $row->id }}</td>
			<td>{{ $row->request->user->information->avaya }}</td>
			<td>{{ $row->request->user->username }}</td>
			<td>{{ $row->request->user->name }}</td>
			<td>{{ $row->request->user->information->wp }}</td>
			<td>{{ $row->request->user->information->skill }}</td>
			<td>{{ $row->forecast->shift_date }}</td>
			<td>{{ date('h:i A' ,strtotime($row->forecast->time_start)) }} </td>
			<td>{{ date('h:i A' ,strtotime($row->forecast->time_end)) }}</td>
		</tr>
	@endforeach
</table>