routes/web.php
	$this->get('/', 'PolicyController@index')->name('policy');
});

$this->get('/login', 'Auth\LoginController@showLoginForm_main')->name('landing');
#$this->name('login')->get('/', 'Auth\LoginController@showLoginForm');
$this->post('/login', 'Auth\LoginController@login')->name('login');

Route::prefix('tf')
->middleware(['center.check'])
->group(function(){
	$this->get('/', 'Auth\LoginController@index');
	$this->get('{center}', 'Auth\LoginController@showLoginForm')->name('center.login');
});


Route::prefix('password')
->group(function(){
	$this->get('reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	$this->post('reset', 'Auth\ResetPasswordController@reset');
	$this->get('reset/{token}/{u?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

	// via sq
	$this->get('security', 'Auth\ForgotPasswordController@security')->name('password.security');
	$this->post('security/request', 'Auth\ForgotPasswordController@submitUsername')->name('password.security.request');
	$this->get('security/question/{q}', 'Auth\ForgotPasswordController@request')->name('password.security.question');
	$this->post('security/reset', 'Auth\ForgotPasswordController@submitSecurity')->name('password.security.reset');

	// via email
	$this->post('email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes [/]
|--------------------------------------------------------------------------
*/
Route::prefix('portal')
->middleware(['auth', 'noob'])
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');

	$this->get('/', 'HomeController@index')->name('home');
	$this->get('schedule/{id}', 'HomeController@schedule_json')->name('schedule_json');
    /*
	|--------------------------------------------------------------------------
	| Mail Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('mail')
	->group(function(){
		Route::get('welcome', 'MailController@sendWelcomeMail')->name('mail.welcome');
	});
    /*
	|--------------------------------------------------------------------------
	| Starter Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('start')
	->middleware('start')
	->group(function(){
		Route::get('/', 'StartController@start')->name('start');
		Route::get('reset', 'StartController@reset')->name('start.reset');
		Route::post('reset', 'StartController@submitReset')->name('start.submitReset');
		Route::get('security', 'StartController@security')->name('start.security');
		Route::post('security', 'StartController@submitSecurity')->name('start.submitSecurity');
	});

	/*
	|--------------------------------------------------------------------------
	| Admin Routes
	|--------------------------------------------------------------------------
	*/
	#Route::resource('users', 'UsersController', [ 'roles' => ['administrator'] ]);

	
	/*
	|--------------------------------------------------------------------------
	| Schedule Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('schedules')
    ->middleware('root')
	->group(function(){
		Route::name('ss_center_we')->get('week-ending/{center_id?}', 'ShiftSwapSchedulesController@center_week_ending');
		Route::name('ss_center_schedule')->get('records/{center_id?}/{week_ending?}', 'ShiftSwapSchedulesController@center_schedule');
	});
	Route::resource('schedules', 'ShiftSwapSchedulesController', [ 'roles' => ['administrator'] ]);

	
	/*
	|--------------------------------------------------------------------------
	| Root Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('admin')
    	->middleware('root')
		->group(function(){
		Route::name('impersonate')->get('impersonate/take/{userid}', 'Admin\ImpersonateController@take', ['as' => 'admin']);

    	Route::prefix('user')
		->group(function(){
			Route::resource('upload', 'Admin\UsersUploadController', ['as' => 'user'])->only(['index', 'store']);
			#Route::name('user.upload')->get('upload', 'Admin\UsersUploadController@create');
			#Route::name('user.upload-submit')->get('upload-submit', 'Admin\UsersUploadController@store');
			Route::name('user.generate-password')->get('generate-password/{id}', 'Admin\UsersController@generate_password');
		});

		Route::resource('user', 'Admin\UsersController', ['as' => 'admin']);
		Route::resource('schedule', 'Admin\SchedulesController', ['as' => 'admin']);
		Route::resource('mail-recipients', 'Admin\MailRecipientsController', ['as' => 'admin']);
		Route::get('password-generator/{number?}', 'Admin\PasswordGeneratorController@index', ['as' => 'admin'])->name('admin.password-generator.index');

		Route::name('home-password')->get('passwords/{number}', 'HomeController@passwords');
	});

	Route::name('impersotate.leave')->get('impersonate/leave', 'Admin\ImpersonateController@leave', ['as' => 'admin'])->middleware(['start']);
	/*
	|--------------------------------------------------------------------------
	| Shift Swap Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('shift-swap')
	->group(function(){
		Route::get('search', 'ShiftSwapInformationController@search_json')->name('ss_search_json');
		Route::get('details-json/{id}', 'ShiftSwapInformationController@details_json')->name('ss_details_json');
		Route::get('record/{id?}', 'ShiftSwapInformationController@shift_swap_record')->name('ss_request_history_json');
		Route::get('week-ending-and-my-shift-date/{id}', 'ShiftSwapInformationController@ss_we_and_my_sd')->name('ss_we_and_my_sd');
		#Route::get('buddy-shift-date', 'ShiftSwapInformationController@ss_buddy_shift_date')->name('ss_buddy_shift_date');

		Route::post('request-confirmation', 'ShiftSwapController@request_confirmation')->name('ss_confirmation');

		Route::get('history/{type}', 'ShiftSwapMyRequestController@index')->name('ss_history');

		Route::group(['middleware' => 'admin'], function(){
	    	Route::resource('ss-reports', 'ShiftSwapReportsController')->only(['index', 'show']);


			Route::get('schedule-upload/utilization', 'ShiftSwapScheduleUploadController@utilization')->name('schedule-upload.utilization');
	    	Route::resource('schedule-upload', 'ShiftSwapScheduleUploadController')->only(['index', 'store']);
	    	Route::resource('enterprise-reports', 'ShiftSwapReportsEnterpriseController')->only(['index', 'show']);
		});
	});
	Route::resource('shift-swap', 'ShiftSwapController')->only(['index', 'store']);
	/*
	|--------------------------------------------------------------------------
	| VTO Routes
	|--------------------------------------------------------------------------
	*/
    Route::prefix('forecast')
	->group(function(){
		Route::name('forecast.calendar')->get('calendar', 'ForecastController@calendar');
		Route::name('forecast.list')->get('list/{date?}', 'ForecastController@list');
		Route::get('skills-wps-json/{center?}', 'ForecastController@skills_wps_json')->name('skills_wps_json');

	    Route::prefix('vot')
		->group(function(){
			Route::name('vot.calendar')->get('calendar', 'ForecastVOTController@calendar');
			Route::name('vot.list')->get('list/{date?}/{schedule?}', 'ForecastVOTController@list');
			Route::name('vot.submit')->post('submit', 'ForecastVOTController@submit');
		});
		Route::resource('vot', 'ForecastVOTController');

	    Route::prefix('vto')
		->group(function(){
			Route::name('vto.calendar')->get('calendar', 'ForecastVTOController@calendar');
			Route::name('vto.list')->get('list/{date?}/{schedule?}', 'ForecastVTOController@list');
			Route::name('vto.submit')->post('submit', 'ForecastVTOController@submit');
			Route::name('vto.mail')->get('mail', 'ForecastCronJobController@vto_email');
		});
		Route::resource('vto', 'ForecastVTOController');

		Route::group(['middleware' => 'admin'], function(){
			Route::resource('vf-reports', 'ForecastReportsController')->only(['index', 'show']);
			Route::resource('vot-enterprise-reports', 'ForecastReportsEnterpriseController')->only(['index', 'show']);
		});
		Route::resource('utilization', 'ForecastUtilizationController', ['as' => 'forecast'])->only(['index', 'create']);
		Route::resource('utilization-detailed', 'ForecastUtilizationDetailedController', ['as' => 'forecast'])->only(['create']);
		Route::resource('upload', 'ForecastUploadController', ['as' => 'forecast'])->only(['index', 'store']);
	});
	Route::resource('forecast', 'ForecastController')->only(['index', 'create', 'store']);
	/*
	|--------------------------------------------------------------------------
	| Absence Replacement
	|--------------------------------------------------------------------------
	*/
    Route::prefix('absence')
	->group(function(){
		Route::name('absence.calendar')->get('calendar', 'AbsenceController@calendar');
		Route::name('absence.list')->get('list', 'AbsenceController@list');
		Route::name('absence.application')->get('application/{shift_date}/{schedule}', 'AbsenceController@application');
		Route::name('absence.application_post')->post('application', 'AbsenceController@application_post');
		Route::name('absence.approve')->get('{id}/{absence_id}/approve', 'AbsenceController@approve');
		Route::name('absence.deny')->get('{id}/{absence_id}/deny', 'AbsenceController@deny');

		Route::resource('replacement', 'AbsenceReplacementController');
	});
	Route::resource('absence', 'AbsenceController');
	/*
	|--------------------------------------------------------------------------
	| VTO Routes
	|--------------------------------------------------------------------------
	*/
	Route::get('account/download', 'UserAccountController@download')->name('account.download');
	Route::resource('account', 'UserAccountController')->only(['store', 'edit', 'update']);
});

Route::prefix('cron')

app/SwapAgentReqeust.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\SwapType;
use App\SwapAgentSchedule;
use \carbon\Carbon;
use DB;
use Auth;

class SwapAgentReqeust extends Model
{
    public $table = "swap_agent_reqeusts";
    public $timestamps = true;

    protected $dates = [
        'week_ending', 'employee_shift_date', 'buddy_shift_date', 
        'before_expiration_date', 'expiration_date', 
        'created_at', 'updated_at', 'deleted_at'
    ];

    protected $fillable = [
    	'swap_type', 'center_id', 'week_ending', 'status', 
    	'user_id', 'employee_shift_date', 'employee_schedule', 
    	'buddy_user_id', 'buddy_shift_date', 'buddy_schedule', 
        'before_expiration_date', 'expiration_date', 
    	'created_at', 'updated_at', 'deleted_at'
	];

	public function user()
	{
        return $this->belongsTo('App\User', 'user_id', 'id')->withTrashed();
	}

	public function buddy_user()
	{
        return $this->belongsTo('App\User', 'buddy_user_id', 'id')->withTrashed();
	}

    public function user_information()
    {
        return $this->belongsTo('App\SwapAgentInformation', 'user_id', 'user_id');
    }

    public function buddy_user_information()
    {
        return $this->belongsTo('App\SwapAgentInformation', 'buddy_user_id', 'user_id');
    }

    public function getSwapMailTemplateAttribute()
    {
        $swap_type = $this->swap_type;

        if($swap_type == 'sd')
        {
            return 'single-day';
        }
        elseif($swap_type == 'srd')
        {
            return 'single-rest-day';
        }
        elseif($swap_type == '2rd')
        {
            return '2-rest-day';
        }
    }

    public function getSwapTypeNameAttribute()
    {
        $swap_type = $this->swap_type;

        $row = SwapType::whereAbbr($swap_type)->first();

        if(is_null($row))
        {
            return 'SHIFT REST DAY';
        }
        return $row->name;
    }

    public function getStatusTypeAttribute()
    {
        $status = $this->status;
        $expiration_date = $this->expiration_date;
        $datetime = Carbon::now();

        if(is_null($status))
        {
            if($datetime->gte($expiration_date))
            {
                return 'expired';
            }
            return 'pending';
        }
        elseif($status == 0)
        {
            return 'denied';
        }
        elseif($status == 1)
        {
            return 'approved';
        }
        elseif($status == 3)
        {
            return 'cancel';
        }
    }

    public function get_rest_day($week_ending, $user_id)
    {
        $days = '';
        $rows = SwapAgentSchedule::whereUserId($user_id)->whereWeekEnding($week_ending)->whereSchedule('Off')
                ->orderBy('shift_date', 'ASC')->get([ DB::raw('DATE_FORMAT(shift_date, \'%a\') shift_date_f') ]);

        foreach ($rows as $row)
        {
            $days .= $row->shift_date_f . '-';
        }

        return substr($days, 0, -1);
    }

    public function get_rest_date($week_ending, $user_id)
    {
        $days = '';
        $user = Auth::user();
        $two_rd =   SwapAgentReqeust::whereSwapType('2rd')->whereStatus(1)->whereWeekEnding($week_ending)
                ->where(function($query) use ($user_id){
                    $query->where('user_id', $user_id)->orWhere('buddy_user_id', $user_id);
                })->first();

        if(!is_null($two_rd))
        {
            if($two_rd->user_id == $user_id)
            {
                $user_id = $two_rd->buddy_user_id;
            }
            else
            {
                $user_id = $two_rd->user_id;
            }
        }

        $rows = SwapAgentSchedule::whereUserId($user_id)->whereWeekEnding($week_ending)->whereSchedule('Off')->orderBy('shift_date', 'ASC')->get();

        foreach ($rows as $row)
        {
            $shift_date = $row->shift_date;
            if(is_null($two_rd))
            {
                $srd =  SwapAgentReqeust::whereSwapType('srd')->whereStatus(1)->whereWeekEnding($week_ending)
                        ->where(function($query) use ($shift_date){
                            $query->where('employee_shift_date', $shift_date)->orWhere('buddy_shift_date', $shift_date);
                        })
                        ->where(function($query) use ($user_id){
                            $query->where('user_id', $user_id)->orWhere('buddy_user_id', $user_id);
                        })
                        ->first();

                if(!is_null($srd))
                {
                    if($srd->user_id == $user_id)
                    {
                        $shift_date = $srd->buddy_shift_date->toDateString();
                        #$shift_date = $this->date_format($srd->buddy_shift_date);
                    }
                    else
                    {
                        $shift_date = $srd->employee_shift_date->toDateString();
                        #$shift_date = $this->date_format($srd->employee_shift_date);
                    }
                }
            }

            $days .= $this->date_format($shift_date, $user->center_id);
        }

        if($user->center_id == 1)
        {
            return substr($days, 0, -3);
        }

        return substr($days, 0, -5);
    }

    public function date_format($date, $center_id)
    {
        if($center_id == 1)
        {
            return date('D', strtotime($date)) . ' - ';
        }

        return date('Y-m-d', strtotime($date)) . ' and ';
    }
    /*
    public function get_rest_date($week_ending, $user_id)
    {
        $days = '';
        $sr =   SwapAgentReqeust::whereSwapType('2rd')->whereStatus(1)->whereWeekEnding($week_ending)
                ->where(function($query) use ($user_id){
                    $query->where('user_id', $user_id)->orWhere('buddy_user_id', $user_id);
                })->first();

        if(!is_null($sr))
        {
            if($sr->user_id == $user_id)
            {
                $user_id = $sr->buddy_user_id;
            }
            else
            {
                $user_id = $sr->user_id;
            }
        }

        $rows = SwapAgentSchedule::whereUserId($user_id)->whereWeekEnding($week_ending)->whereSchedule('Off')
                ->orderBy('shift_date', 'ASC')->get();


        foreach ($rows as $row)
        {
            $days .= $row->shift_date . ' and ';
        }

        return substr($days, 0, -5);
    }
    */
}

resources/views/shift-swap/my-request.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
  <div class="columns">
    <div class="column is-12">
      <h3 class="title is-4">{{ $type }}</h3>
      <table class="table is-bordered is-narrow is-fullwidth">
        <thead>
          <tr>
            <th width="4%"></th>
            <th width="15%" class="has-text-centered">Request Id</th>
            <th width="15%">Swap Type</th>
            <th width="15%" class="has-text-centered">Week Ending</th>
            <th width="25%">Buddy Name</th>
            <th width="16%">Created At</th>
            <th width="10%" class="has-text-centered">Status</th>
          </tr>
        </thead>
        <tbody>
        @foreach($rows as $row)
          <tr>
            <td class="has-text-centered">
              <a href="#" onclick="details({{ $row->id }})"><i class="fa fa-list"></i></a>
            </td>
            <td class="has-text-centered">{{ $row->id }}</td>
            <td class="is-uppercase">{{ $row->swap_type_name }}</td>
            <td class="has-text-centered">{{ $row->week_ending->toDateString() }}</td>
            <td>{{ $row->buddy_user->name }}</td>
            <td>{{ $row->created_at }}</td>
            <td class="has-text-centered is-uppercase">
              @if(is_null($row->status))
                @if($row->status_type == 'expired')
                <span class="tag is-danger">{{ $row->status_type }}</span>
                @else
                <span class="tag is-info">{{ $row->status_type }}</span>
                @endif
              @elseif($row->status == 0)
              <span class="tag is-warning">{{ $row->status_type }}</span>
              @elseif($row->status == 1)
              <span class="tag is-success">{{ $row->status_type }}</span>
              @elseif($row->status == 3)
              <span class="tag is-warning">{{ $row->status_type }}</span>
              @endif
              
            </td>
          </tr>
        @endforeach
        </tbody>
      </table>
      {!! $rows->links('vendor.pagination.default') !!}
    </div>
  </div>
</div>

<div id="modal-details" class="modal">
  <div class="modal-background" onclick="modal_hide()"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Request Details</p>
      <button class="delete" aria-label="close" onclick="modal_hide()"></button>
    </header>
    <section class="modal-card-body">

      <table class="table is-fullwidth is-narrow is-bordered">
        <tr>
          <th class="has-text-centered">My Old Schedule</th>
          <th class="has-text-centered">My New Schedule</th>
        </tr>
        <tr>
          <td class="has-text-centered" id="my_old_schedule"><span class="tag is-dark">2018-06-10 4:00 PM - 12:00 AM</span></td>
          <td class="has-text-centered" id="my_new_schedule"><span class="tag is-success">2018-06-10 4:00 PM - 12:00 AM</span></td>
        </tr>
        <tr>
          <th colspan="2">&nbsp;</th>
        </tr>
        <tr>
          <th class="has-text-centered">Buddy Old Schedule</th>
          <th class="has-text-centered">Buddy New Schedule</th>
        </tr>
        <tr>
          <td class="has-text-centered" id="buddy_old_schedule"><span class="tag is-dark">2018-06-10 4:00 PM - 12:00 AM</span></td>
          <td class="has-text-centered" id="buddy_new_schedule"><span class="tag is-success">2018-06-10 4:00 PM - 12:00 AM</span></td>
        </tr>
      </table>

    </section>
  </div>
</div>

<script type="text/javascript">
  var xhr_records = null;

  function details(id)
  {
    xhr_records = $.ajax({
      type : 'get',
      url : '{{ route("ss_request_history_json") }}/' + id,
      cache : false,
      dataType : "json",
      beforeSend: function(xhr){
        if (xhr_records != null)
        {
          xhr_records.abort();
        }
      }
    }).done(function(result) {


      var my_old = '';
      var my_new = '';

      var buddy_old = '';
      var buddy_new = '';

      var swap_type = result[0]['swap_type'];

      var employee_shift_date = result[0]['employee_shift_date'];
      var employee_schedule = result[0]['employee_schedule'];
      var buddy_shift_date = result[0]['buddy_shift_date'];
      var buddy_schedule = result[0]['buddy_schedule'];

      if(swap_type == '2rd' || swap_type == 'shrd')
      {

        $.each(employee_shift_date, function(key, value){
          my_new += '<span class="tag is-dark">' + value + '</span> ';
          buddy_old += '<span class="tag is-success">' + value + '</span> ';
        });

        $.each(buddy_shift_date, function(key, value){
          buddy_new += '<span class="tag is-dark">' + value + '</span> ';
          my_old += '<span class="tag is-success">' + value + '</span> ';
        });
      }
      else
      {
        var my_old = '<span class="tag is-dark">' + employee_shift_date + ' ' + employee_schedule + '</span>';
        var my_new = '<span class="tag is-success">' + buddy_shift_date + ' ' + buddy_schedule + '</span>';

        var buddy_old =  '<span class="tag is-dark">' + buddy_shift_date + ' ' + buddy_schedule + '</span>';
        var buddy_new =  '<span class="tag is-success">' + employee_shift_date + ' ' + employee_schedule + '</span>';
      }

      $('#my_old_schedule').html(my_old);
      $('#my_new_schedule').html(my_new);

      $('#buddy_old_schedule').html(buddy_old);
      $('#buddy_new_schedule').html(buddy_new);

      $('#modal-details').addClass('is-active');

    }).fail(function(jqXHR, textStatus) {
    });
  }

  function modal_hide()
  {
    $('#modal-details').removeClass('is-active');
  }
</script>
@endsection

resources/views/shift-swap/schedule-upload.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <div class="columns">
    <div class="column is-3"></div>
    <div class="column is-6">
      <div class="card">
        <div class="card-header">
          <label class="card-header-title label" for="search_avaya">Upload Schedule Swap</label>
        </div>
        <div class="card-content">
          <form id="schedule-upload" method="post" action="{{ route('schedule-upload.store') }}">

            <div class="notification is-info">
              CSV file format is required.<br/>
              Always remove the Header.<br/>
              Always follow the column arrangement.<br/> 
              Download template <a href="{{ asset('templates/schedule-template.csv') }}">here</a>.
            </div>
            <div class="field has-addons">
              <div class="control has-icons-left is-expanded">
                <div class="file">
                  <label class="file-label">
                    <input class="file-input" type="file" id="file" name="schedule">
                    <span class="file-cta">
                      <span class="file-icon">
                        <i class="fa fa-upload"></i>
                      </span>
                      <span class="file-label">
                        Choose a file…
                      </span>
                    </span>
                  </label>
                </div>
              </div>
              <div class="control">
                {!! csrf_field() !!}
                <button class="button is-info" type="submit" id="schedule-upload-btn" disabled="">Upload</button>
              </div>
            </div>

          </form>
          <div class="error-message"></div>
        </div>
      </div>
    </div>
    <div class="column is-3"></div>
  </div>
</div>

@endsection

@section('scripts')
<script type="text/javascript">
  var xhr_file = null;
  var file_arr = [];
  var file_chunk = [];

  $(function(){
    $('#file').change(function(e){
      var file = e.target.files[0];
      if(file['type'] != 'application/vnd.ms-excel')
      {
        $('.error-message').html('<br /><div class="notification is-warning">Only CSV file extension is allowed!</div><br />');
      }
      else
      {
        Papa.parse(file, {
          header: false,
          dynamicTyping: true,
          skipEmptyLines: true,
          complete: function(results, file) {
            file_arr = results.data;
            file_chunk = results.data;
            //console.log(file_arr);
            $('#schedule-upload-btn').attr('disabled', false);
          }// End complete: function(results, file)
        });
      }

    });

    $('#schedule-upload').submit(function(e){
      if($('#file').val() == '')
      {
        $('.error-message').html('<div class="notification is-warning">File is required!</div><br />');
        return false;
      }

      var method = $(this).attr('method');
      var url = $(this).attr('action');
      var token = $('input[name=_token').val();
      //var center = $('#center').val();
      var parameters = 'row=' + JSON.stringify(file_chunk) + '&_token=' + token;
      xhr_file = $.ajax({
          type : method,
          url : url,
          data : parameters,
          cache : false,
          async: false,
          dataType : "json",
          beforeSend: function(xhr){
            $('#schedule-upload-btn').attr('disabled', true);
            $('.error-message').html('<br /><div class="notification is-info has-text-centered"><img src="{{ asset("img/loading/2.gif") }}" title="Uploading" /></div>');
            if (xhr_file != null)
            {
                xhr_file.abort();
            }
          }
      }).done(function(data){
        xhr_file = null;
        var messages = 'Done uploading Schedules!<hr />';
        $.each(data['errors'], function(key, value){
          messages += '' + value + '<br />';
        });

        $('.error-message').html('<br /><div class="notification is-success">' + messages + '</div>');
        //console.log(data);
      }).fail(function(jqXHR, textStatus){
          //console.log('Request failed: ' + textStatus);
      });


      return false;
      e.preventDefault();
    });
  });
</script>
@endsection